using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AttendanceMonitoring.Models;

/// <summary>
/// A single per-calendar-date shift assignment. The schedule is now
/// stored as concrete dates (e.g. 2026-05-18) instead of a weekly
/// template (Mon=0..Sun=6). Admins author entries one date at a time
/// from the month editor, and the clock-in guardrail looks up today's
/// PHT date directly.
/// </summary>
public class ScheduleEntry
{
    public int Id { get; set; }

    public int UserId { get; set; }
    public User? User { get; set; }

    /// <summary>The Philippine-time calendar date this shift covers.</summary>
    public DateOnly WorkDate { get; set; }

    public TimeOnly? StartTime { get; set; }
    public TimeOnly? EndTime { get; set; }

    public bool IsWorking { get; set; } = true;

    /// <summary>
    /// Categorisation of the shift used by the late-arrival / grace-period
    /// rules. One of <c>"Onsite" | "Offsite" | "Dayoff" | "Onleave" | "Holiday"</c>. Stored as a
    /// short string so it can be filtered / displayed without a lookup
    /// table. Null on legacy rows authored before this column shipped —
    /// callers normalise via <see cref="EffectiveWorkType"/>.
    /// </summary>
    [MaxLength(16)]
    public string? WorkType { get; set; }

    [MaxLength(200)]
    public string? Note { get; set; }

    /// <summary>
    /// Marker for who authored this row. <c>null</c> = manual entry from
    /// the per-user editor, <c>"roster"</c> = generated by the Coalition
    /// roster grid. Used by the roster save handler to clean up its own
    /// rows on the next save without touching manual edits.
    /// </summary>
    [MaxLength(20)]
    public string? Source { get; set; }

    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>0 = Monday … 6 = Sunday — derived from <see cref="WorkDate"/>.</summary>
    [NotMapped]
    public int Weekday => ((int)WorkDate.DayOfWeek + 6) % 7;

    [NotMapped]
    public string WeekdayName => Constants.WeekdayNames[Weekday];

    /// <summary>1..6: which week-of-month bucket this date falls in (day 1–7 = 1, 8–14 = 2, …).</summary>
    [NotMapped]
    public int WeekOfMonth => ((WorkDate.Day - 1) / 7) + 1;

    [NotMapped]
    public double Hours
    {
        get
        {
            if (!IsWorking || StartTime is null || EndTime is null) return 0.0;
            var startMin = StartTime.Value.Hour * 60 + StartTime.Value.Minute;
            var endMin = EndTime.Value.Hour * 60 + EndTime.Value.Minute;
            var diff = endMin - startMin;
            // Cross-midnight shifts (e.g. 22:00 → 06:00, 16:00 → 00:00) are
            // represented with EndTime <= StartTime. Treat the end time as
            // being on the next day so Support / overnight rotations don't
            // collapse to zero hours.
            if (diff <= 0) diff += 24 * 60;
            return Math.Round(diff / 60.0, 2);
        }
    }

    /// <summary>
    /// Scheduled work duration in whole minutes, end-time treated as the
    /// next day if it's &lt;= start (overnight shift). 0 for non-working
    /// rows or rows missing either bound.
    /// </summary>
    [NotMapped]
    public int ScheduledMinutes
    {
        get
        {
            if (!IsWorking || StartTime is null || EndTime is null) return 0;
            var startMin = StartTime.Value.Hour * 60 + StartTime.Value.Minute;
            var endMin = EndTime.Value.Hour * 60 + EndTime.Value.Minute;
            var diff = endMin - startMin;
            if (diff <= 0) diff += 24 * 60;
            return diff;
        }
    }

    public bool CoversTime(TimeOnly t)
    {
        if (!IsWorking || StartTime is null || EndTime is null) return false;
        var start = StartTime.Value;
        var end = EndTime.Value;
        // Same-day shift: start <= t <= end.
        if (end > start) return start <= t && t <= end;
        // Wrap-around shift (e.g. 22:00 -> 06:00): t is covered if it falls
        // after the start OR before the end (on the following day).
        return t >= start || t <= end;
    }

    /// <summary>
    /// True when a local wall-clock timestamp falls inside this concrete
    /// schedule row, including an overnight end on the following date.
    /// </summary>
    public bool CoversLocal(DateTime localDateTime)
    {
        if (!IsWorking || StartTime is null || EndTime is null) return false;

        var start = WorkDate.ToDateTime(StartTime.Value);
        var endDate = EndTime.Value <= StartTime.Value
            ? WorkDate.AddDays(1)
            : WorkDate;
        var end = endDate.ToDateTime(EndTime.Value);
        return localDateTime >= start && localDateTime <= end;
    }

    /// <summary>
    /// True when the provided work-type label is treated as a non-working
    /// day (no shift window): Dayoff, Onleave, or Holiday.
    /// </summary>
    public static bool IsNonWorkingType(string? workType)
    {
        if (string.IsNullOrWhiteSpace(workType)) return false;
        var v = workType.Trim();
        return v.Equals("Dayoff", StringComparison.OrdinalIgnoreCase)
            || v.Equals("Onleave", StringComparison.OrdinalIgnoreCase)
            || v.Equals("Holiday", StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Returns the normalised working-type label
    /// (<c>"Onsite" | "Offsite" | "Dayoff" | "Onleave" | "Holiday"</c>)
    /// the late-arrival rules
    /// should evaluate against. Legacy rows that pre-date the explicit
    /// <see cref="WorkType"/> column are mapped from <see cref="IsWorking"/>
    /// (true ⇒ Onsite, false ⇒ Dayoff) and from a <see cref="Note"/> of
    /// "Offsite" so the existing offsite-day editor keeps working.
    /// </summary>
    [NotMapped]
    public string EffectiveWorkType
    {
        get
        {
            if (!string.IsNullOrWhiteSpace(WorkType))
            {
                var v = WorkType.Trim();
                if (v.Equals("Onsite", StringComparison.OrdinalIgnoreCase))  return "Onsite";
                if (v.Equals("Offsite", StringComparison.OrdinalIgnoreCase)) return "Offsite";
                if (v.Equals("Dayoff",  StringComparison.OrdinalIgnoreCase)) return "Dayoff";
                if (v.Equals("Onleave", StringComparison.OrdinalIgnoreCase)) return "Onleave";
                if (v.Equals("Holiday", StringComparison.OrdinalIgnoreCase)) return "Holiday";
            }
            if (!IsWorking) return "Dayoff";
            if (!string.IsNullOrWhiteSpace(Note)
                && Note.Contains("Offsite", StringComparison.OrdinalIgnoreCase))
            {
                return "Offsite";
            }
            return "Onsite";
        }
    }

    /// <summary>
    /// CSI standard working hours: 09:00 – 18:00.
    /// Anchored here so every "default schedule" callsite renders the
    /// same numbers — the Profile / Dashboard week strip, the schedule
    /// editor prefill, and any future reports.
    /// </summary>
    public static readonly TimeOnly DefaultStartTime = new(9, 0);
    public static readonly TimeOnly DefaultEndTime = new(18, 0);

    /// <summary>
    /// Returns a synthesized "default" schedule entry for a given date.
    /// CSI standard: Monday–Friday is a 09:00–18:00 Onsite shift; the
    /// weekend (Saturday / Sunday) is a day off. This is used when the
    /// admin has not yet authored a specific row for the date so the
    /// employee's dashboard / profile shows the company-standard shift
    /// instead of a confusing all-week "Day off". The result is NOT
    /// persisted (Id stays 0) — it's purely a display-time stand-in.
    /// </summary>
    public static ScheduleEntry CsiDefaultFor(int userId, DateOnly date)
    {
        var isWeekday = date.DayOfWeek >= DayOfWeek.Monday
                        && date.DayOfWeek <= DayOfWeek.Friday;
        if (isWeekday)
        {
            return new ScheduleEntry
            {
                UserId = userId,
                WorkDate = date,
                IsWorking = true,
                StartTime = DefaultStartTime,
                EndTime = DefaultEndTime,
                WorkType = "Onsite",
            };
        }
        return new ScheduleEntry
        {
            UserId = userId,
            WorkDate = date,
            IsWorking = false,
            WorkType = "Dayoff",
        };
    }
}
